# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f43e66a1ac773b2324469ed4af8766d6cc44d492e38697476549a46519c277941f734b963a5b0b6175848a9973ee6eec4810873e19dab91c9682d5e059d2bee

test:
  secret_key_base: fe6315d7332b6890aa36121b51cc88eda5d71688acd3e5b280a12d4b1965c32f9143a6ae767cfeee04acc550fee8991c4c56a1c5c9cd9d3e99dd160d42b252e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
